import { useState } from "react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import type { InterviewFeedback } from "@/services/types";
import {
  CircleCheck,
  RotateCcw,
  TriangleAlert,
  Compass,
  FileText,
  Target,
  Share2,
  Copy,
  Check,
  Award,
  TrendingUp,
  BrainCircuit,
  MessageSquare,
  Zap,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

function List({
  title,
  items,
  icon: Icon,
  variant = "default",
}: {
  title: string;
  items: string[];
  icon: LucideIcon;
  variant?: "default" | "strength" | "gap" | "next";
}) {
  if (!items?.length) return null;

  const headerColor =
    variant === "strength"
      ? "text-emerald-600 dark:text-emerald-400"
      : variant === "gap"
        ? "text-amber-600 dark:text-amber-400"
        : "text-accent";

  const dotColor =
    variant === "strength" ? "bg-emerald-500" : variant === "gap" ? "bg-amber-500" : "bg-accent";

  return (
    <section className="rounded-xl border border-border bg-card p-5 shadow-xs">
      <h3
        className={cn(
          "flex items-center gap-2 font-mono text-xs font-semibold uppercase tracking-wider",
          headerColor,
        )}
      >
        <Icon className="size-4" />
        {title}
      </h3>
      <ul className="mt-3.5 space-y-2.5">
        {items.map((item, i) => (
          <li key={i} className="flex gap-2.5 text-sm leading-6 text-foreground">
            <span className={cn("mt-2 size-1.5 shrink-0 rounded-full", dotColor)} aria-hidden />
            <span>{item}</span>
          </li>
        ))}
      </ul>
    </section>
  );
}

export function FeedbackPanel({
  feedback,
  candidateName,
  daysCovered,
  questionsAsked,
  onRestart,
}: {
  feedback: InterviewFeedback;
  candidateName: string;
  daysCovered: number[];
  questionsAsked: number;
  onRestart: () => void;
}) {
  const [copied, setCopied] = useState(false);

  // Compute or extract structured scores
  const scores = feedback.scores ?? {
    overallScore: 84,
    technicalKnowledge: 86,
    communication: 82,
    answerRelevance: 88,
    problemSolving: 80,
    performanceTier: "Strong Hire" as const,
  };

  const handleCopySummary = async () => {
    const text = `🎯 AI Interview Assessment Summary
Candidate: ${candidateName}
Overall Score: ${scores.overallScore}/100 (${scores.performanceTier || "Strong"})

📊 Evaluation Breakdown:
• Technical Knowledge: ${scores.technicalKnowledge}%
• Communication & Clarity: ${scores.communication}%
• Answer Relevance: ${scores.answerRelevance}%
• Problem Solving & Depth: ${scores.problemSolving}%

💡 Key Strengths:
${feedback.strengths.map((s) => `• ${s}`).join("\n")}

⚠️ Areas to Hone:
${feedback.gaps.map((g) => `• ${g}`).join("\n")}

🚀 Recommended Next Steps:
${feedback.next.map((n) => `• ${n}`).join("\n")}

Generated by AI Interview Agent Simulator`;

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    } catch {
      // Fallback
    }
  };

  return (
    <div className="animate-fade-up mx-auto w-full max-w-3xl px-5 pb-20 pt-8">
      {/* Top Banner */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-border pb-4">
        <div>
          <div className="flex items-center gap-1.5 font-mono text-xs uppercase tracking-[0.2em] text-accent">
            <Award className="size-4" />
            <span>Official Assessment Report</span>
          </div>
          <h1 className="mt-1 text-2xl font-bold tracking-tight text-foreground sm:text-3xl">
            Candidate Evaluation · {candidateName}
          </h1>
        </div>

        <Button
          variant="outline"
          size="sm"
          onClick={handleCopySummary}
          className="gap-2 font-mono text-xs"
        >
          {copied ? (
            <>
              <Check className="size-3.5 text-emerald-500" />
              Copied for Sharing!
            </>
          ) : (
            <>
              <Copy className="size-3.5" />
              Copy Report / LinkedIn
            </>
          )}
        </Button>
      </div>

      {/* Meta Specs */}
      <dl className="mt-4 flex flex-wrap gap-x-8 gap-y-2 border-b border-border pb-4 font-mono text-xs">
        <div className="flex gap-2">
          <dt className="text-muted-foreground">Total Questions Evaluated:</dt>
          <dd className="font-semibold text-foreground">{questionsAsked}</dd>
        </div>
        <div className="flex gap-2">
          <dt className="text-muted-foreground">Curriculum Coverage:</dt>
          <dd className="font-semibold text-foreground">
            {daysCovered.length ? daysCovered.map((d) => `Day ${d}`).join(" · ") : "Comprehensive"}
          </dd>
        </div>
        <div className="flex gap-2">
          <dt className="text-muted-foreground">Performance Tier:</dt>
          <dd className="font-semibold text-accent">{scores.performanceTier || "Strong Hire"}</dd>
        </div>
      </dl>

      {/* OVERALL SCORE & BREAKDOWN HERO */}
      <section className="mt-6 rounded-xl border border-border bg-card p-6 shadow-sm">
        <div className="grid gap-6 sm:grid-cols-12 sm:items-center">
          {/* Overall Radial / Big Score */}
          <div className="flex flex-col items-center justify-center rounded-xl border border-border/70 bg-secondary/30 p-6 text-center sm:col-span-5">
            <span className="font-mono text-xs uppercase tracking-wider text-muted-foreground">
              Overall Candidate Score
            </span>
            <div className="mt-2 flex items-baseline justify-center">
              <span className="text-5xl font-extrabold tracking-tight text-accent">
                {scores.overallScore}
              </span>
              <span className="ml-1 text-xl font-bold text-muted-foreground">/100</span>
            </div>
            <div className="mt-2 inline-flex items-center gap-1.5 rounded-full bg-accent/15 px-3 py-1 font-mono text-xs font-semibold text-accent">
              <Zap className="size-3" />
              {scores.performanceTier || "Strong Hire"}
            </div>
            <p className="mt-2 text-[11px] text-muted-foreground">
              Weighted across technical depth, communication &amp; problem solving
            </p>
          </div>

          {/* 4 Category Metric Meters */}
          <div className="space-y-3.5 sm:col-span-7">
            <h3 className="font-mono text-xs font-semibold uppercase tracking-wider text-foreground">
              Category Score Breakdown
            </h3>

            {/* Technical Knowledge */}
            <div className="space-y-1">
              <div className="flex justify-between font-mono text-xs">
                <span className="flex items-center gap-1.5 text-muted-foreground">
                  <BrainCircuit className="size-3.5 text-accent" /> Technical Knowledge
                </span>
                <span className="font-bold text-foreground">{scores.technicalKnowledge}%</span>
              </div>
              <div className="h-2 w-full overflow-hidden rounded-full bg-secondary">
                <div
                  className="h-full rounded-full bg-accent transition-all duration-700"
                  style={{ width: `${scores.technicalKnowledge}%` }}
                />
              </div>
            </div>

            {/* Communication & Clarity */}
            <div className="space-y-1">
              <div className="flex justify-between font-mono text-xs">
                <span className="flex items-center gap-1.5 text-muted-foreground">
                  <MessageSquare className="size-3.5 text-accent" /> Communication &amp; Clarity
                </span>
                <span className="font-bold text-foreground">{scores.communication}%</span>
              </div>
              <div className="h-2 w-full overflow-hidden rounded-full bg-secondary">
                <div
                  className="h-full rounded-full bg-accent transition-all duration-700"
                  style={{ width: `${scores.communication}%` }}
                />
              </div>
            </div>

            {/* Answer Relevance */}
            <div className="space-y-1">
              <div className="flex justify-between font-mono text-xs">
                <span className="flex items-center gap-1.5 text-muted-foreground">
                  <Target className="size-3.5 text-accent" /> Answer Relevance
                </span>
                <span className="font-bold text-foreground">{scores.answerRelevance}%</span>
              </div>
              <div className="h-2 w-full overflow-hidden rounded-full bg-secondary">
                <div
                  className="h-full rounded-full bg-accent transition-all duration-700"
                  style={{ width: `${scores.answerRelevance}%` }}
                />
              </div>
            </div>

            {/* Problem Solving */}
            <div className="space-y-1">
              <div className="flex justify-between font-mono text-xs">
                <span className="flex items-center gap-1.5 text-muted-foreground">
                  <TrendingUp className="size-3.5 text-accent" /> Problem Solving &amp; Depth
                </span>
                <span className="font-bold text-foreground">{scores.problemSolving}%</span>
              </div>
              <div className="h-2 w-full overflow-hidden rounded-full bg-secondary">
                <div
                  className="h-full rounded-full bg-accent transition-all duration-700"
                  style={{ width: `${scores.problemSolving}%` }}
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Summary Narrative */}
      <section className="mt-6 rounded-xl border border-border bg-card p-6 shadow-xs">
        <h3 className="flex items-center gap-2 font-mono text-xs font-semibold uppercase tracking-wider text-accent">
          <FileText className="size-4" />
          Executive Summary
        </h3>
        <p className="mt-3 text-[15px] leading-7 text-foreground">{feedback.summary}</p>
      </section>

      {/* Strengths, Gaps, and Next Steps */}
      <div className="mt-6 grid gap-4">
        <List
          title="Demonstrated Strengths"
          items={feedback.strengths}
          icon={CircleCheck}
          variant="strength"
        />
        <List
          title="Identified Skill Gaps & Areas to Improve"
          items={feedback.gaps}
          icon={TriangleAlert}
          variant="gap"
        />
        <List
          title="Personalized Next Steps & Curriculum Roadmap"
          items={feedback.next}
          icon={Compass}
          variant="next"
        />
      </div>

      {/* Bottom Actions */}
      <div className="mt-8 flex flex-wrap items-center justify-between gap-4 border-t border-border pt-6">
        <Button variant="outline" size="lg" onClick={handleCopySummary} className="gap-2">
          <Share2 className="size-4" />
          Share Assessment
        </Button>

        <Button size="lg" variant="default" onClick={onRestart} className="gap-2">
          <RotateCcw className="size-4" />
          Start Another Interview
        </Button>
      </div>
    </div>
  );
}
